---
# Playbook to stop FileMaker Server on Ubuntu
- name: Stop FileMaker Server
  hosts: all
  gather_facts: no
  become: true
  tasks:
    - name: Stop FileMaker Server
      ansible.builtin.command:
        cmd: fmsadmin stop server -y -u fmadmin
      become_user: root
      ignore_errors: yes
