---
# Playbook to stop FileMaker Server service
- name: stop filemaker server
  hosts: all
  gather_facts: yes
  become: true
  tasks:
    - name: Stop FileMaker Server service
      ansible.builtin.service:
        name: fmshelper
        state: stopped
